### ISSUE TITLE
Collab?

### ISSUE THREAD

**Issue by kyjus25** [noffle/hyperpad-desktop#6]
Hi sir,

I’ve forked your code and began work on somewhat of a refactor under the same name as your project. I’ve converted the idea into Angular and I’m using Pusher to handle code collaboration capabilities. I’d love to collaborate on the project since the idea was yours originally. I think it’s a really cool idea that hasn’t been done before. You’re welcome to contribute to my project and we can consider it a V2 or Hyperpad, or if you’d prefer continuing with the project you already have, I can change the name of my project to keep them separate and I’ll give credit to your project in my releases. Currently I have a branch under my fork called “refactor”. That’s where my work will be if you’re interested in checking it out. I will be working on it more tonight and I’ll  get it to a presentable point by tomorrow.

Interested in your thoughts. Hopefully this will reach your inbox. Seems GitHub no longer supports direct messaging.

Thanks!

**Comment by hackergrrl** [comment]
Cool fork. I like the logo & name.

I looked at the Pusher website, and it looks like a cloud service? I wasn't able to the find the peer-to-peer parts in your new app. Being decentralized and serverless was the core motivation behind hyperpad, though it's nice that you found the core editor or some ideas useful for your project too.

**Comment by kyjus25** [comment]
Ah, that makes sense. Yes, it's using Pusher. I agree, eventually I might take it step further and implement some rxJS observable listeners to convert it to serverless. Another idea for another day. Thanks for taking a look!
